# Generated by Django 5.1.5 on 2025-03-15 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bundles', '0002_bundle_discount_bundle_price'),
        ('products', '0004_alter_product_from_age_alter_product_to_age'),
        ('shops', '0001_initial'),
        ('users', '0003_clientuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('idempotency', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overall_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('PARTIALLY_GIVEN', 'PARTIALLY_GIVEN'), ('TOTALLY_GIVEN', 'TOTALLY_GIVEN'), ('CANCELLED', 'CANCELLED')], default='WAITING')),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.clientuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overall_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('WAITING_FOR_COURIER', 'WAITING_FOR_COURIER'), ('GIVEN_TO_COURIER', 'GIVEN_TO_COURIER'), ('GIVEN_TO_CUSTOMER', 'GIVEN_TO_CUSTOMER'), ('CANCELLED', 'CANCELLED')], default='WAITING_FOR_COURIER')),
                ('item_type', models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('BUNDLE', 'BUNDLE')])),
                ('bundle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='bundles.bundle')),
                ('client_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.clientorder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
