# Generated by Django 5.1.5 on 2025-03-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0002_bundle_discount_bundle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
