# Generated by Django 5.1.5 on 2025-03-15 10:43

import apps.services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceproviderrating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.services.models.upload_service_personal_information_profile_photo),
        ),
    ]
