# Generated by Django 5.1.5 on 2025-03-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_details_alter_serviceprovider_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProviderRating',
        ),
    ]
