# Generated by Django 5.1.5 on 2025-03-17 05:24

import apps.users.kids.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('level_name', models.CharField(max_length=255)),
                ('level_position', models.PositiveSmallIntegerField(unique=True)),
                ('from_xp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_xp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.users.kids.models.upload_kid_image)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True, default='')),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='users.clientuser')),
                ('kid_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='kids.kidlevel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
