# Generated by Django 5.1.5 on 2025-03-17 05:44

import apps.users.kids.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidlevel',
            name='level_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.kids.models.upload_kid_level_image),
        ),
    ]
