# Generated by Django 5.1.5 on 2025-03-17 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_kidlevel_level_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='kid_level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='kids.kidlevel'),
        ),
    ]
