# Generated by Django 5.1.5 on 2025-02-13 19:01

import apps.shops.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=255)),
                ('time_zone', models.CharField(choices=[('-12', 'GMT-12'), ('-11', 'GMT-11'), ('-10', 'GMT-10'), ('-9', 'GMT-9'), ('-8', 'GMT-8'), ('-7', 'GMT-7'), ('-6', 'GMT-6'), ('-5', 'GMT-5'), ('-4', 'GMT-4'), ('-3', 'GMT-3'), ('-2', 'GMT-2'), ('-1', 'GMT-1'), ('+0', 'GMT+0'), ('+1', 'GMT+1'), ('+2', 'GMT+2'), ('+3', 'GMT+3'), ('+4', 'GMT+4'), ('+5', 'GMT+5'), ('+6', 'GMT+6'), ('+7', 'GMT+7'), ('+8', 'GMT+8'), ('+9', 'GMT+9'), ('+10', 'GMT+10'), ('+11', 'GMT+11'), ('+12', 'GMT+12'), ('+13', 'GMT+13'), ('+14', 'GMT+14')], default='+5', max_length=8)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='shops.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('blocked', models.BooleanField(default=False)),
                ('open_from', models.TimeField(null=True)),
                ('open_until', models.TimeField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.shops.models.upload_shop_image)),
                ('rating', models.FloatField(default=0, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('two_gis_link', models.CharField(max_length=255, null=True)),
                ('contacts', models.TextField(null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
