# Generated by Django 5.1.5 on 2025-03-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='rating',
        ),
    ]
