# Generated by Django 5.1.5 on 2025-03-14 16:42

import apps.shops.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.shops.products.models.upload_product_category_icon),
        ),
    ]
