# Generated by Django 5.1.5 on 2025-03-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='from_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='to_age',
            field=models.PositiveIntegerField(),
        ),
    ]
