# Generated by Django 5.1.5 on 2025-03-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_size_productcategory_is_eatable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('GR', 'GR'), ('KG', 'KG'), ('L', 'L'), ('PC', 'PC')], max_length=100),
        ),
    ]
