# Generated by Django 5.1.5 on 2025-02-19 07:46

import apps.shops.commodity_groups.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0002_shopcategory_shop_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to=apps.shops.commodity_groups.models.upload_commodity_group_category_icon)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_group_categories', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommodityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=apps.shops.commodity_groups.models.upload_commodity_group_image)),
                ('description', models.TextField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_groups', to='shops.shop')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_groups', to='commodity_groups.commoditygroupcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
