# Generated by Django 5.1.5 on 2025-02-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditygroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
