# Generated by Django 5.1.5 on 2025-03-14 16:42

import apps.shops.commodity_groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_groups', '0002_alter_commoditygroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditygroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.shops.commodity_groups.models.upload_commodity_group_image),
        ),
        migrations.AlterField(
            model_name='commoditygroupcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.shops.commodity_groups.models.upload_commodity_group_category_icon),
        ),
    ]
