# Generated by Django 5.1.5 on 2025-03-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectrating',
            name='status',
            field=models.CharField(choices=[('ON_MODERATION', 'ON_MODERATION'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='ON_MODERATION'),
        ),
    ]
