# Generated by Django 5.1.5 on 2025-03-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepricelist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
