# Generated by Django 5.1.5 on 2025-03-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_coursepricelist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepricelist',
            name='payment_period',
            field=models.CharField(choices=[('monthly', 'monthly'), ('weekly', 'weekly'), ('daily', 'daily'), ('hourly', 'hourly')], default='monthly', max_length=255),
        ),
    ]
