# Generated by Django 5.1.5 on 2025-03-05 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('card_hash', models.CharField(max_length=19)),
                ('card_month', models.CharField(max_length=2)),
                ('card_year', models.CharField(max_length=4)),
                ('bank', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('card_3ds', models.BooleanField()),
                ('status', models.CharField(max_length=255)),
                ('card_id', models.IntegerField()),
                ('card_token', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
